name: Build on release
run-name: ${{ github.actor }} building release ${{github.event.release.tag_name}}
on: 
  release: 
    types: created
jobs:
  Build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./ReceiptStorage.TelegramBot//Dockerfile
          push: true
          tags: ivang2896044/receiptstorage:${{github.event.release.tag_name}}